spring.application.name=com.OnlineExam
spring.datasource.url=jdbc:mysql://localhost:3306/examdb
spring.datasource.username=root
spring.datasource.password=Mugesh123#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8082
